#!/usr/bin/env python3
import clipboard
from factorio.blueprints import Blueprint


def try_call(f):
    try:
        return f()
    except Exception:
        return None


def print_json_representation(code: str):
    import base64
    import json
    import zlib

    compressed = base64.b64decode(code[1:])
    decoded = json.loads(zlib.decompress(compressed).decode())
    print(decoded)


original_code = clipboard.paste()
print_json_representation(original_code)
blueprint = Blueprint.decode(original_code)
print(blueprint)
new_code = blueprint.encode()
print(f"old code: {len(original_code)} characters")
print(f"new code: {len(new_code)} characters")
# print(int(blueprint))
for _, attrs in blueprint.entities.values():
    if "recipe" in attrs and attrs["recipe"] != "copper-cable":
        del attrs["recipe"]
if tile_code := try_call(lambda: blueprint.to_tile_code()):
    print(f" as tile: {len(tile_code)} characters")
    decoded_tile = Blueprint.from_tile_code(tile_code)
    # print(decoded_tile)
    assert blueprint == decoded_tile
    clipboard.copy(tile_code)
    print("Tile code has been copied to your clipboard")
else:
    clipboard.copy(new_code)
    print("New code has been copied to your clipboard")
