#!/usr/bin/env python3
import clipboard
from factorio.blueprints import Blueprint


def try_call(f):
    try:
        return f()
    except Exception:
        return None


def print_json_representation(code: str):
    import base64
    import json
    import zlib

    compressed = base64.b64decode(code[1:])
    decoded = json.loads(zlib.decompress(compressed).decode())
    print(json.dumps(decoded, indent=2))


original_code = clipboard.paste()
print_json_representation(original_code)
